services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "48000:8000"
    env_file:
      - ./backend/.env
    environment:
      - FRONTEND_URL=http://localhost:3000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - BACKEND_INTERNAL_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
